### ISSUE TITLE
JSON output support

### ISSUE THREAD

**Issue by joewood** [sanagama/vscode-mssql#3]
Great extension. Would be great if you could include JSON formatted output for the resultset (from queries with `FOR JSON PATH`).

**Comment by edudutra** [comment]
I think it would be nice to just have an option to show the outputs in JSON, regardless the if the query has the option `FOR JSON PATH`, since this option only works in SQL 2016. The results returned from [node-mssql](https://github.com/patriksimek/node-mssql) already come in JSON, so I guess it would be a simple thing to do.
I could give it a try, if you are accepting PRs. 
Really great extension, by the way. I was thinking on developing something like this myself, but then I found it.

**Comment by sanagama** [comment]
Hi edudutra, I'll gladly accept PRs if you are able to work on this. Please let me know.

**Comment by sanagama** [comment]
Hi, Thanks for your feedback. This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Here's a link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

Please can you try this and open an issue if you are still having problems: https://github.com/Microsoft/vscode-mssql/issues

Regards,
Sanjay
